export const mockUsers = [
  {
    id: 1,
    username: "ana",
    name: "Ana Pereira",
  },
  {
    id: 2,
    username: "carlos",
    name: "Carlos Méndez",
  },
];

export const mockLocales = [
  {
    id: 1,
    name: "Café Central",
    type: "CAFETERIA",
    priceRange: "ECONOMICO",
    city: "Montevideo",
    zone: "Centro",
    address: "Av. 18 de Julio 1234",
    hours: "08:00 - 20:00",
    description: "Cafetería clásica en el corazón de Montevideo, ideal para un desayuno o merienda tranquila.",
    photos: [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
    ],
    rating: 4.5,
    userId: 1,
    reviews: [
      { id: 1, rating: 5, comment: "Excelente café y atención!", userId: 2, userName: "Carlos Méndez" },
      { id: 2, rating: 4, comment: "Muy buen lugar para trabajar.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 2,
    name: "El Parrillero",
    type: "RESTAURANTE",
    priceRange: "MEDIO",
    city: "Montevideo",
    zone: "Pocitos",
    address: "Bulevar España 2345",
    hours: "12:00 - 23:00",
    description: "El mejor asado de Pocitos. Cortes premium a la parrilla con guarniciones caseras.",
    photos: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
    ],
    rating: 4.8,
    userId: 2,
    reviews: [
      { id: 3, rating: 5, comment: "El mejor asado que comí en Montevideo.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 3,
    name: "Sushi Nikkei",
    type: "RESTAURANTE",
    priceRange: "ALTO",
    city: "Montevideo",
    zone: "Punta Carretas",
    address: "Ellauri 350",
    hours: "19:00 - 23:30",
    description: "Fusión peruano-japonesa con los mejores ingredientes frescos del día.",
    photos: [
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
    ],
    rating: 4.6,
    userId: 1,
    reviews: [
      { id: 4, rating: 5, comment: "Increíble fusión, muy recomendable.", userId: 2, userName: "Carlos Méndez" },
      { id: 5, rating: 4, comment: "Caro pero vale la pena.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 4,
    name: "La Churrasquería",
    type: "FOOD_TRUCK",
    priceRange: "ECONOMICO",
    city: "Colonia del Sacramento",
    zone: "Centro Histórico",
    address: "Feria del Puerto, Puesto 5",
    hours: "11:00 - 16:00",
    description: "Food truck con chivitos y churrascos al paso. Clásico y rápido.",
    photos: [
      "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800",
    ],
    rating: 4.2,
    userId: 2,
    reviews: [
      { id: 6, rating: 4, comment: "Chivito espectacular, buen precio.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 5,
    name: "Bar El Mingaco",
    type: "BAR",
    priceRange: "MEDIO",
    city: "Montevideo",
    zone: "Cordón",
    address: "Gaboto 1456",
    hours: "18:00 - 02:00",
    description: "Bar de barrio con buena música, cócteles y picadas para compartir.",
    photos: [
      "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800",
    ],
    rating: 4.3,
    userId: 1,
    reviews: [
      { id: 7, rating: 4, comment: "Buena onda y buenos tragos.", userId: 2, userName: "Carlos Méndez" },
    ],
  },
];

export const mockPlatos = [
  {
    id: 1,
    name: "Bife Ancho con Guarnición",
    category: "PRINCIPAL",
    localId: 2,
    localName: "El Parrillero",
    city: "Montevideo",
    zone: "Pocitos",
    price: 890,
    description: "Corte premium con papas fritas y ensalada mixta.",
    photos: [
      "https://images.unsplash.com/photo-1558030006-450675393462?w=800",
    ],
    createdAt: "2026-01-15",
    userId: 2,
    rating: 4.9,
    reviews: [
      { id: 1, rating: 5, comment: "El mejor bife que probé.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 2,
    name: "Capuchino Doble",
    category: "BEBIDA",
    localId: 1,
    localName: "Café Central",
    city: "Montevideo",
    zone: "Centro",
    price: 180,
    description: "Capuchino con leche entera y espuma cremosa. Incluye galletita.",
    photos: [
      "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800",
    ],
    createdAt: "2026-02-03",
    userId: 1,
    rating: 4.5,
    reviews: [
      { id: 2, rating: 5, comment: "Perfecto para empezar el día.", userId: 2, userName: "Carlos Méndez" },
    ],
  },
  {
    id: 3,
    name: "Tabla de Sushi Nikkei",
    category: "PRINCIPAL",
    localId: 3,
    localName: "Sushi Nikkei",
    city: "Montevideo",
    zone: "Punta Carretas",
    price: 1450,
    description: "Tabla para dos con 16 piezas de rolls y nigiris de autor.",
    photos: [
      "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800",
    ],
    createdAt: "2026-01-28",
    userId: 1,
    rating: 4.7,
    reviews: [
      { id: 3, rating: 5, comment: "Presentación impecable, sabor increíble.", userId: 2, userName: "Carlos Méndez" },
    ],
  },
  {
    id: 4,
    name: "Chivito al Pan",
    category: "PRINCIPAL",
    localId: 4,
    localName: "La Churrasquería",
    city: "Colonia del Sacramento",
    zone: "Centro Histórico",
    price: 320,
    description: "Chivito clásico con jamón, queso, huevo y tomate. El original uruguayo.",
    photos: [
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    ],
    createdAt: "2026-02-10",
    userId: 2,
    rating: 4.3,
    reviews: [
      { id: 4, rating: 4, comment: "Clásico uruguayo bien hecho.", userId: 1, userName: "Ana Pereira" },
    ],
  },
  {
    id: 5,
    name: "Picada Mingaco",
    category: "ENTRADA",
    localId: 5,
    localName: "Bar El Mingaco",
    city: "Montevideo",
    zone: "Cordón",
    price: 550,
    description: "Tabla con fiambres, quesos, aceitunas y tostadas. Ideal para compartir.",
    photos: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    ],
    createdAt: "2026-03-01",
    userId: 1,
    rating: 4.4,
    reviews: [
      { id: 5, rating: 4, comment: "Buena picada para arrancar la noche.", userId: 2, userName: "Carlos Méndez" },
    ],
  },
  {
    id: 6,
    name: "Brownie con Helado",
    category: "POSTRE",
    localId: 1,
    localName: "Café Central",
    city: "Montevideo",
    zone: "Centro",
    price: 220,
    description: "Brownie tibio de chocolate con dos bochas de helado de crema.",
    photos: [
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
    ],
    createdAt: "2026-02-20",
    userId: 2,
    rating: 4.6,
    reviews: [
      { id: 6, rating: 5, comment: "Impresionante el brownie, lo recomiendo.", userId: 1, userName: "Ana Pereira" },
    ],
  },
];